# Generated by Django 2.0.2 on 2018-02-08 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=10)),
                ('subj_list', models.CharField(max_length=50)),
                ('num_of_students', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=15)),
                ('mark', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stud_mat', models.CharField(max_length=5)),
                ('stud_name', models.CharField(max_length=30)),
                ('stud_surname', models.CharField(max_length=30)),
                ('stud_dob', models.DateTimeField(verbose_name='birth date')),
                ('stud_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Classe')),
            ],
        ),
        migrations.AddField(
            model_name='marks',
            name='stud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Students'),
        ),
    ]
